// Generated by scripts/optimize-images.py; originals remain in public/.
export const imageVariants: Record<
  string,
  { src: string; width: number; height: number }[]
> = {
  'img/boda/carrusel1.jpeg': [
    {
      src: 'img/optimized/carrusel1-480.webp',
      width: 480,
      height: 411,
    },
    {
      src: 'img/optimized/carrusel1-960.webp',
      width: 960,
      height: 823,
    },
    {
      src: 'img/optimized/carrusel1-1600.webp',
      width: 1600,
      height: 1371,
    },
    {
      src: 'img/optimized/carrusel1-2400.webp',
      width: 2400,
      height: 2056,
    },
  ],
  'img/boda/carrusel2.jpeg': [
    {
      src: 'img/optimized/carrusel2-480.webp',
      width: 480,
      height: 720,
    },
    {
      src: 'img/optimized/carrusel2-960.webp',
      width: 960,
      height: 1440,
    },
    {
      src: 'img/optimized/carrusel2-1600.webp',
      width: 1600,
      height: 2400,
    },
    {
      src: 'img/optimized/carrusel2-2400.webp',
      width: 2400,
      height: 3600,
    },
  ],
  'img/boda/carrusel3.png': [
    {
      src: 'img/optimized/carrusel3-480.webp',
      width: 480,
      height: 720,
    },
    {
      src: 'img/optimized/carrusel3-960.webp',
      width: 960,
      height: 1440,
    },
    {
      src: 'img/optimized/carrusel3-1600.webp',
      width: 1600,
      height: 2400,
    },
    {
      src: 'img/optimized/carrusel3-2400.webp',
      width: 2400,
      height: 3600,
    },
  ],
  'img/boda/carrusel4.png': [
    {
      src: 'img/optimized/carrusel4-480.webp',
      width: 480,
      height: 720,
    },
    {
      src: 'img/optimized/carrusel4-960.webp',
      width: 960,
      height: 1440,
    },
    {
      src: 'img/optimized/carrusel4-1600.webp',
      width: 1600,
      height: 2400,
    },
    {
      src: 'img/optimized/carrusel4-2400.webp',
      width: 2400,
      height: 3600,
    },
  ],
  'img/boda/carrusel5.jpeg': [
    {
      src: 'img/optimized/carrusel5-480.webp',
      width: 480,
      height: 320,
    },
    {
      src: 'img/optimized/carrusel5-960.webp',
      width: 960,
      height: 640,
    },
    {
      src: 'img/optimized/carrusel5-1600.webp',
      width: 1600,
      height: 1067,
    },
    {
      src: 'img/optimized/carrusel5-2400.webp',
      width: 2400,
      height: 1601,
    },
  ],
  'img/boda/fotoBoda.png': [
    {
      src: 'img/optimized/fotoBoda-480.webp',
      width: 480,
      height: 719,
    },
    {
      src: 'img/optimized/fotoBoda-960.webp',
      width: 960,
      height: 1438,
    },
    {
      src: 'img/optimized/fotoBoda-1025.webp',
      width: 1025,
      height: 1535,
    },
  ],
  'img/boda/alejandra&dionicio-61.png': [
    {
      src: 'img/optimized/alejandra&dionicio-61-480.webp',
      width: 480,
      height: 320,
    },
    {
      src: 'img/optimized/alejandra&dionicio-61-960.webp',
      width: 960,
      height: 640,
    },
    {
      src: 'img/optimized/alejandra&dionicio-61-1600.webp',
      width: 1600,
      height: 1067,
    },
    {
      src: 'img/optimized/alejandra&dionicio-61-2400.webp',
      width: 2400,
      height: 1600,
    },
    {
      src: 'img/optimized/alejandra&dionicio-61-3600.webp',
      width: 3600,
      height: 2400,
    },
  ],
  'ceremonia.png': [
    {
      src: 'img/optimized/ceremonia-480.webp',
      width: 480,
      height: 329,
    },
    {
      src: 'img/optimized/ceremonia-960.webp',
      width: 960,
      height: 658,
    },
    {
      src: 'img/optimized/ceremonia-1104.webp',
      width: 1104,
      height: 757,
    },
  ],
  'celebracion.png': [
    {
      src: 'img/optimized/celebracion-480.webp',
      width: 480,
      height: 281,
    },
    {
      src: 'img/optimized/celebracion-960.webp',
      width: 960,
      height: 563,
    },
    {
      src: 'img/optimized/celebracion-1396.webp',
      width: 1396,
      height: 818,
    },
  ],
};
