"""Build display-sized WebP copies without replacing the original photos.

Run from FRONT with Python and Pillow: python scripts/optimize-images.py
"""

import json
import subprocess
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUTPUT = PUBLIC / "img" / "optimized"
SOURCES = [
    "img/boda/carrusel1.jpeg",
    "img/boda/carrusel2.jpeg",
    "img/boda/carrusel3.png",
    "img/boda/carrusel4.png",
    "img/boda/carrusel5.jpeg",
    "img/boda/fotoBoda.png",
    "img/boda/alejandra&dionicio-61.png",
    "ceremonia.png",
    "celebracion.png",
]

OUTPUT.mkdir(parents=True, exist_ok=True)
manifest = {}
for source in SOURCES:
    original = PUBLIC / source
    with Image.open(original) as opened:
        photo = ImageOps.exif_transpose(opened)
        profile = opened.info.get("icc_profile")
        variants = []
        widths = sorted({min(width, photo.width) for width in (480, 960, 1600, 2400)})
        # The full-width closing background also needs its native resolution
        # on large/high-density screens; galleries do not need oversized files.
        if source == "img/boda/alejandra&dionicio-61.png" and photo.width > widths[-1]:
            widths.append(photo.width)
        for width in widths:
            height = round(photo.height * width / photo.width)
            resized = photo.resize((width, height), Image.Resampling.LANCZOS)
            filename = f"{original.stem}-{width}.webp"
            options = {"quality": 95, "method": 4}
            if profile:
                options["icc_profile"] = profile
            resized.save(OUTPUT / filename, "WEBP", **options)
            variants.append({"src": f"img/optimized/{filename}", "width": width, "height": height})
        manifest[source] = variants
        print(f"{source}: {original.stat().st_size:,} bytes -> "
              f"{(PUBLIC / variants[-1]['src']).stat().st_size:,} bytes (largest variant)")

target = ROOT / "src" / "TiendaOnline" / "data" / "imageVariants.ts"
target.write_text(
    "// Generated by scripts/optimize-images.py; originals remain in public/.\n"
    "export const imageVariants: Record<string, { src: string; width: number; height: number }[]> = "
    + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8",
)
subprocess.run(
    ["node", str(ROOT / "node_modules" / "prettier" / "bin" / "prettier.cjs"),
     "--write", str(target)],
    cwd=ROOT,
    check=True,
)
